// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PacificTours.Data;

#nullable disable

namespace PacificTours.Migrations.BookingDb
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20240523092736_BookingMigration")]
    partial class BookingMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("PacificTours.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BookingAmountPaid")
                        .HasColumnType("REAL");

                    b.Property<string>("BookingCustomerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookingEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookingPackageDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("BookingPrice")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("BookingStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
