ENV ASPNETCORE_ENVIRONMENT=Production
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["PacificTours/PacificTours.csproj", "PacificTours/"]
RUN dotnet restore "PacificTours/PacificTours.csproj"
COPY . .
WORKDIR "/src/PacificTours"
RUN dotnet build "PacificTours.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PacificTours.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PacificTours.dll"]